// Code generated by Kitex v0.8.0. DO NOT EDIT.

package echo1

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/apache/thrift/lib/go/thrift"

	"github.com/felix021/dubbo-p1/kitex_gen/java"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.TProtocol(nil)
	_ = java.KitexUnusedProtection
)

type TestService1EchoArgs struct {
	Req *EchoRequest `thrift:"req,1" frugal:"1,default,EchoRequest" json:"req"`
}

func NewTestService1EchoArgs() *TestService1EchoArgs {
	return &TestService1EchoArgs{}
}

func (p *TestService1EchoArgs) InitDefault() {
	*p = TestService1EchoArgs{}
}

var TestService1EchoArgs_Req_DEFAULT *EchoRequest

func (p *TestService1EchoArgs) GetReq() (v *EchoRequest) {
	if !p.IsSetReq() {
		return TestService1EchoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TestService1EchoArgs) SetReq(val *EchoRequest) {
	p.Req = val
}

func (p *TestService1EchoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TestService1EchoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestService1EchoArgs(%+v)", *p)
}
func (p *TestService1EchoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TestService1EchoResult struct {
	Success *EchoResponse `thrift:"success,0,optional" frugal:"0,optional,EchoResponse" json:"success,omitempty"`
}

func NewTestService1EchoResult() *TestService1EchoResult {
	return &TestService1EchoResult{}
}

func (p *TestService1EchoResult) InitDefault() {
	*p = TestService1EchoResult{}
}

var TestService1EchoResult_Success_DEFAULT *EchoResponse

func (p *TestService1EchoResult) GetSuccess() (v *EchoResponse) {
	if !p.IsSetSuccess() {
		return TestService1EchoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TestService1EchoResult) SetSuccess(x interface{}) {
	p.Success = x.(*EchoResponse)
}

func (p *TestService1EchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestService1EchoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestService1EchoResult(%+v)", *p)
}
func (p *TestService1EchoResult) GetResult() interface{} {
	return p.Success
}
